# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# User configuration
#

# Export environment variable
export RUSTC_WRAPPER=/usr/bin/sccache

# Alias
alias g.='gitui'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log'
alias gs='git status'

alias l='ls -latr'
alias la='ls -a'
alias ll='ls -ltr'
alias lsp='find "$PWD" -maxdepth 1'

alias pacmans='sudo ROZB3_PAC_SKIP=1 pacman'
alias parus='ROZB3_PAC_SKIP=1 paru'

alias nnn='nnn -dcoH'
alias yv='youtube-viewer'
alias yva='youtube-viewer -a'

# keybindings
bindkey "^[ " autosuggest-accept
bindkey "^[^M" autosuggest-execute

# load seperated config files
for conf in "$HOME/.config/zsh/config.d/"*.zsh; do
  source "${conf}"
done
unset conf

#
# End of user configuration
#

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
